"""Initial schema with all tables

Revision ID: 4166023639f2
Revises: 
Create Date: 2025-11-06 17:40:36.899395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4166023639f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('WEB_SEARCH', 'EMAIL_DRAFT', 'EMAIL_SEND', 'OTHER_TOOL', name='enum_ai_action_type'), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', name='enum_ai_action_status'), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_action_type'), 'ai_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_ai_actions_conversation_id'), 'ai_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_created_at'), 'ai_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_actions_message_id'), 'ai_actions', ['message_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_status'), 'ai_actions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_actions_user_id'), 'ai_actions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gmail_draft_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_filename'), 'email_attachments', ['filename'], unique=False)
    op.create_index(op.f('ix_email_attachments_gmail_draft_id'), 'email_attachments', ['gmail_draft_id'], unique=False)
    op.create_table('gmail_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('message_id_gmail', sa.String(), nullable=True),
    sa.Column('to_recipients', sa.JSON(), nullable=True),
    sa.Column('cc_recipients', sa.JSON(), nullable=True),
    sa.Column('bcc_recipients', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'FAILED', name='enum_gmail_draft_status'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_drafts_message_id_gmail'), 'gmail_drafts', ['message_id_gmail'], unique=False)
    op.create_index(op.f('ix_gmail_drafts_sent_at'), 'gmail_drafts', ['sent_at'], unique=False)
    op.create_index(op.f('ix_gmail_drafts_status'), 'gmail_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_gmail_drafts_user_id'), 'gmail_drafts', ['user_id'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_vector_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.Enum('CONVERSATION', 'EMAIL', 'WEB_SEARCH', 'CUSTOM', name='enum_source_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_chunks_conversation_id'), 'memory_chunks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_message_id'), 'memory_chunks', ['message_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_source_type'), 'memory_chunks', ['source_type'], unique=False)
    op.create_index(op.f('ix_memory_chunks_user_id'), 'memory_chunks', ['user_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_citations_rank'), 'message_citations', ['rank'], unique=False)
    op.create_index(op.f('ix_message_citations_source_url'), 'message_citations', ['source_url'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='enum_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'MARKDOWN', 'CODE', name='enum_content_type'), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_tool_name'), 'messages', ['tool_name'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oauth_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_account_email'), 'oauth_accounts', ['account_email'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('web_search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.Enum('BING', 'SERPAPI', name='enum_web_search_engine'), nullable=True),
    sa.Column('raw_results', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_search_queries_created_at'), 'web_search_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_web_search_queries_engine'), 'web_search_queries', ['engine'], unique=False)
    op.create_index(op.f('ix_web_search_queries_query'), 'web_search_queries', ['query'], unique=False)
    op.create_index(op.f('ix_web_search_queries_user_id'), 'web_search_queries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_web_search_queries_user_id'), table_name='web_search_queries')
    op.drop_index(op.f('ix_web_search_queries_query'), table_name='web_search_queries')
    op.drop_index(op.f('ix_web_search_queries_engine'), table_name='web_search_queries')
    op.drop_index(op.f('ix_web_search_queries_created_at'), table_name='web_search_queries')
    op.drop_table('web_search_queries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_email'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_messages_tool_name'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_citations_source_url'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_rank'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_memory_chunks_user_id'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_source_type'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_message_id'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_conversation_id'), table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_gmail_drafts_user_id'), table_name='gmail_drafts')
    op.drop_index(op.f('ix_gmail_drafts_status'), table_name='gmail_drafts')
    op.drop_index(op.f('ix_gmail_drafts_sent_at'), table_name='gmail_drafts')
    op.drop_index(op.f('ix_gmail_drafts_message_id_gmail'), table_name='gmail_drafts')
    op.drop_table('gmail_drafts')
    op.drop_index(op.f('ix_email_attachments_gmail_draft_id'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_filename'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_actions_user_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_status'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_message_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_created_at'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_conversation_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_action_type'), table_name='ai_actions')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
